info:
  contact: {}
paths:
  /healthcheck:
    get:
      consumes:
      - text/plain
      description: healthcheck for service
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: healthcheck
      tags:
      - healthcheck
swagger: "2.0"
